dataconnector:
  athena:
    uri: http://super-connector.data-connector:8081/api/v1/athena
  mariadb:
    uri: http://super-connector.data-connector:8081/api/v1/mariadb
  mongodb:
    uri: http://mongodb-connector.data-connector:8081
  mysql8:
    uri: http://super-connector.data-connector:8081/api/v1/mysql
  oracle:
    uri: http://super-connector.data-connector:8081/api/v1/oracle
  snowflake:
    uri: http://super-connector.data-connector:8081/api/v1/snowflake
